version: '3.7'

services:
  storage:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - miniodata:/data
    command: server /data
  
  pythonapp:
    image: python-app:1.0
    build:
      context: ./build/python-app
    depends_on:
      - storage
    ports:
      - "${API_PORT}:5000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ./app:/usr/src/app
    command: python app.py

volumes:
  miniodata: