- name: Check if the env file exixts
  stat:
    path: /vagrant/.env
  register: env_file
- name: Copy the env file from sample
  copy:
    remote_src: yes
    src: /vagrant/env-sample
    dest: /vagrant/.env
  when: env_file.stat.exists == False
- name: Change env file permissions
  file:
    path: /vagrant/.env
    mode: go-rwx
- name: Create a minio access key in env file
  lineinfile:
    path: /vagrant/.env
    line: MINIO_ACCESS_KEY={{ lookup('password', 'accesskey chars=ascii_uppercase,digits length=20') }}
  when: env_file.stat.exists == False
- name: Remove the stored access key file
  file:
    path: /vagrant/provisioning/accesskey
    state: absent
- name: Create a minio secret key in env file
  lineinfile:
    path: /vagrant/.env
    line: MINIO_SECRET_KEY={{ lookup('password', 'secretkey chars=ascii_letters,/,digits length=40') }}
  when: env_file.stat.exists == False
- name: Remove the stored secret key file
  file:
    path: /vagrant/provisioning/secretkey
    state: absent
- name: Check if the upload folder exixts
  stat:
    path: /vagrant/app/uploads
  register: upload_folder
- name: Recursive copy of upload folder example
  copy:
    remote_src: yes
    src: /vagrant/uploads
    dest: /vagrant/app
  when: upload_folder.stat.exists == False